language: go

go:
- '1.11'

env:
- GO111MODULE=on

install:
- go get github.com/golang/lint/golint

script:
- golint -set_exit_status ./...
- go test -mod=readonly -coverprofile=profile.cov ./...

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
